version: '3'
services:
  db:
    build: ./postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      API_DB: "api"
      API_DB_USER: "${API_DB_USERNAME}"
      API_DB_PASSWORD: "${API_DB_PASSWORD}"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - traefik_web

  web:
      build:
        context: ./web
        # target: prod
        args:
          REACT_APP_HOST: ${DOMAIN:-betterstreets.co.uk}
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.bs_web.loadbalancer.server.port=80"
        - "traefik.http.routers.bs_web.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.bs_web.service=bs_web"
        - "traefik.http.routers.bs_web.rule=Host(`${DOMAIN:-betterstreets.localhost}`)"
        - "traefik.http.routers.bs_web.tls=true"
      networks:
        - traefik_web
  api:
    # image: ghcr.io/hackthemidlands/htm-achievements/api:${TAG}
    build:
      context: ./api
      # target: prod
      # labels:
      #   org.opencontainers.image.title: achievements-api
      #   org.opencontainers.image.source: https://github.com/HackTheMidlands/htm-achievements
    restart: unless-stopped
    # depends_on:
    #   db:
    #     condition: service_healthy
    labels:
      # - "traefik.http.services.api.loadbalancer.server.port=80"
      # - "traefik.http.routers.api.service=api"
      # - "traefik.enable=true"
      # - "traefik.http.routers.api.tls=true"
      #- "traefik.http.routers.api.rule=Host(`api.${DOMAIN:-badlyparked.localhost}`)"
      # - "traefik.http.routers.api.middlewares=limit"
      # - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=8000000"
      # - "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=origin-list-or-null"
      - "traefik.enable=true"
      - "traefik.http.routers.bs_api.tls=true"
      - "traefik.http.routers.bs_api.tls.certresolver=letsEncrypt"
      -  "traefik.http.services.bs_api.loadbalancer.server.port=80"
      - "traefik.http.routers.bs_api.rule=Host(`${DOMAIN:-betterstreets.localhost}`) && PathPrefix(`/api`)"
      # - "traefik.http.routersbs_api.api.rule=Host(`${DOMAIN:-badlyparked.localhost}`) && PathPrefix(`/api`)"
      # - "traefik.http.routers.api.rule=Host(`${DOMAIN:-api.badlyparked.localhost}`)"
      - "traefik.http.middlewares.strip_api.stripprefix.prefixes=/api"
      - "traefik.http.routers.bs_api.middlewares=strip_api"
        # - "traefik.http.routers.api.middlewares=api-prefix@file"
    environment:
      DOMAIN: "${DOMAIN:-betterstreets.localhost}"
      DATABASE_URL: "postgresql://${API_DB_USERNAME}:${API_DB_PASSWORD}@db/api"
      ADMIN_LIST: "${ADMIN_LIST}"
      SESSION_SECRET: "${SESSION_SECRET}"
      DISCORD_OAUTH_CLIENT_ID: "${DISCORD_OAUTH_CLIENT_ID}"
      DISCORD_OAUTH_CLIENT_SECRET: "${DISCORD_OAUTH_CLIENT_SECRET}"
      TWITTER_OAUTH_CLIENT_ID: "${TWITTER_OAUTH_CLIENT_ID}"
      TWITTER_OAUTH_CLIENT_SECRET: "${TWITTER_OAUTH_CLIENT_SECRET}"
      EXTERNAL_API_TOKEN: "${EXTERNAL_API_TOKEN}"
    networks:
      - traefik_web

  
  # admin:
  #   # image: ghcr.io/hackthemidlands/htm-achievements/admin:${TAG}
  #   build:
  #     context: ./admin
  #     # target: prod
  #     # labels:
  #     #   org.opencontainers.image.title: achievements-admin-ui
  #     #   org.opencontainers.image.source: https://github.com/HackTheMidlands/htm-achievements
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.admin.loadbalancer.server.port=80"
  #     - "traefik.http.routers.admin.service=admin"
  #     - "traefik.http.routers.admin.rule=Host(`${DOMAIN:-betterstreets.localhost}`) && PathPrefix(`/admin`)"
  #     - "traefik.http.routers.admin.priority=100"
  #     # - "traefik.http.routers.admin.middlewares=admin-prefix@file"
  #     - "traefik.http.middlewares.strip_admin.stripprefix.prefixes=/admin"
  #     - "traefik.http.routers.admin.middlewares=strip_admin"
  #     - "traefik.http.routers.admin.tls=true"

networks:
  traefik_web:
    external:
            true

volumes:
  db_data:
